# Generated by Django 4.2.1 on 2023-05-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=8, null=True, verbose_name='dni')),
                ('name', models.CharField(max_length=50, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='apellidos')),
                ('sex', models.IntegerField(blank=True, choices=[(0, 'femenino'), (1, 'masculino')], null=True, verbose_name='sexo')),
                ('title', models.IntegerField(blank=True, choices=[(0, 'tec.'), (1, 'mvz.')], null=True, verbose_name='titulo')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ('name',),
            },
        ),
    ]
